### ISSUE TITLE
add (require 'ess-site) to init.el

### ISSUE THREAD

**Issue by gmounie** [alegrand/RR_MOOC#2]
For babel R evaluation in org-mode, (require 'ess-site) in init.el was required on my Linux install.

**Comment by alegrand** [comment]
Hi,

  this is weird. Can you tell me more about your setup ? On mine, I don't think I ever did something like this. Furthermore, the [ESS manual](https://ess.r-project.org/Manual/ess.html) indicates:

> The ESS initialization process has been further streamlined. If you update the autoloads (which installation from package-install does), you should not need to (require 'ess-site) at all, as autoloads should automatically load ESS when it is needed (e.g. the first time an R buffer is opened).

**Comment by gmounie** [comment]
It may be a bug in the new emacs packaging of Sid.

I use a fresh account on Debian Sid. .emacs.d/init.el is the only configuration of emacs
org 9.1.13
ess-version 17.11
emacs 25.2.2

creating a fresh .org file; creating a block with <r and "summary(cars)" in the block and C-c C-c
I got the error messages:

executing R code block...
ERROR:ess-etc-directory
Relative to ess-lisp-directory, one of the following must exist:
../etc/ess, ../etc, ../../etc/ess or ./etc
org-babel-R-initiate-session: Symbol’s function definition is void: R

**Comment by khinsen** [comment]
I had to add `(require 'ess-site)` as well when I used R from OrgMode under Linux (Guix), but not under macOS. That was during the preparation of the videos, so I was too busy with other things to explore what was going on. But just like @gmounie, I had not installed the packages though the Emacs package manager, so perhaps that matters.

**Comment by alegrand** [comment]
I've added it as it does not hurt anyway. Fixed in af786c7ffe99ed5fe8d471f88b9083a59e3b7350.
